name: Publish

on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write # Required for OIDC
  contents: read
  packages: write

jobs:
  publish-py:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout project
        uses: actions/checkout@v6

      - name: Install Mise
        uses: caido/action-mise-action@v3.2.0
        with:
          working_directory: .
          version: ${{ vars.CI__MISE_VERSION }}

      - name: Install dependencies
        run: uv sync

      - name: Publish caido-server-auth
        uses: ./.github/actions/publish-one
        with:
          project-path: packages/caido-server-auth

      - name: Publish caido-sdk-client
        uses: ./.github/actions/publish-one
        with:
          project-path: packages/caido-sdk-client
